gn: update to 0+git20260226
Add a workaround for -Werror=comment.

Link: https://gn.issues.chromium.org/issues/488456166 ("Compilation
 failure: ../src/gn/header_checker.h:109:3: error: multi-line comment")