linux-kernel: update to 6.18.1
- Refresh Loongson 2K3000 CAN-FD patch, which now supports fractional
  frequency division.
- Add a quirk for Wodposit WPBSNM8-256GTP (NVMe SSD) to disable secondary
  temperature thresholds (reporting 0 for min/max, causing error in
  sensors(1)):

    ERROR: Can't get value of subfeature temp2_min: I/O error
    ERROR: Can't get value of subfeature temp2_max: I/O error

- Backport a fix for warnings during iwlwifi MVM/MLD PTP initialisation.
- Refresh the 3C6000 PCIe link speed quirk: squash the changes, fix the
  fall through logic, and add some output to kernel log.
- Refresh all config for Core and Rustc updates.
- Track patches at AOSC-Tracking/linux @ aosc/v6.18.1
  (HEAD: 4392f441363abdf6fa0a0433d73175a17f493454).